"""
TBAPS — KBT Download Endpoint
==============================
Serves the kbt_identity.json bundle for a specific employee via a
signed, time-limited URL generated by the onboarding service.

GET /api/v1/kbt/download/{employee_id}
  ?expires=<unix_ts>&sig=<hmac>&name=<slug>

Verifies the HMAC signature before serving.
Requires no authentication token (the URL itself is the proof of authorization).

Also exposes:
  POST /api/v1/kbt/resend/{employee_id}   — Admin/Manager/HR: resend onboarding email
"""

import json
import logging
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import JSONResponse, Response
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.core.rbac import require_any_staff
from app.services.kbt_onboarding import (
    verify_signed_download_url,
    run_kbt_onboarding,
    build_identity_bundle,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/kbt", tags=["kbt-download"])


# ── GET /kbt/download/{employee_id} ──────────────────────────────────────────

@router.get("/download/{employee_id}")
async def download_kbt_identity(
    employee_id: str,
    expires: str = Query(..., description="Link expiry Unix timestamp"),
    sig:     str = Query(..., description="HMAC-SHA256 signature"),
    name:    Optional[str] = Query(None, description="Employee name slug (for filename)"),
    db:      AsyncSession = Depends(get_db),
):
    """
    Serve the kbt_identity.json bundle for an employee.

    The URL is signed by the onboarding service and is time-limited (72 hours).
    No JWT required — the signature IS the authorization.

    Response: JSON with Content-Disposition attachment header.
    """
    # Verify the HMAC signature and expiry
    if not verify_signed_download_url(employee_id, expires, sig):
        raise HTTPException(
            status_code=403,
            detail="Download link is invalid or has expired. Request a new onboarding email.",
        )

    # Fetch employee + token from DB
    result = await db.execute(
        text("""
            SELECT e.id::text AS id,
                   e.name,
                   e.email,
                   e.status,
                   e.kbt_token_hash,
                   e.kbt_token_expires_at,
                   e.kbt_generated_at
            FROM   employees e
            WHERE  e.id::text = :id
              AND  e.deleted_at IS NULL
        """),
        {"id": employee_id},
    )
    row = result.fetchone()

    if not row:
        raise HTTPException(status_code=404, detail="Employee not found.")

    if row.status != "active":
        raise HTTPException(status_code=403, detail="Employee account is not active.")

    if not row.kbt_token_hash:
        raise HTTPException(
            status_code=404,
            detail="KBT token not provisioned for this employee. Contact your administrator.",
        )

    # We return a JSON package that scripts/generate_kbt.py can consume,
    # OR the employee downloads directly and places beside the binary.
    # Note: The raw token is NOT returned here — the download URL is meant for
    # the admin/IT team to run generate_kbt.py, not for the employee to
    # reconstruct the token. The actual per-employee binary is packaged using
    # scripts/generate_kbt.py which calls GET /api/v1/kbt/token/{id} (admin auth).
    #
    # What we serve here is the onboarding metadata the IT admin needs.

    from app.core.config import settings

    onboarding_info = {
        "employee_id":    row.id,
        "name":           row.name,
        "email":          row.email,
        "kbt_provisioned": bool(row.kbt_token_hash),
        "kbt_generated_at": row.kbt_generated_at.isoformat() if row.kbt_generated_at else None,
        "kbt_expires_at":   row.kbt_token_expires_at.isoformat() if row.kbt_token_expires_at else None,
        "packaging_instructions": (
            f"Run: python scripts/generate_kbt.py "
            f"--employee-id {row.id} "
            f"--api-url {settings.SERVER_URL} "
            f"--admin-token <ADMIN_JWT> "
            f"--base-binary agent/dist/KBT "
            f"--output dist/employees/KBT_{row.name.replace(' ', '_')}"
        ),
    }

    filename = f"kbt_info_{name or employee_id}.json"
    body = json.dumps(onboarding_info, indent=2).encode("utf-8")

    return Response(
        content=body,
        media_type="application/json",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
            "X-KBT-Employee-ID": employee_id,
        },
    )


# ── POST /kbt/resend/{employee_id} ───────────────────────────────────────────

@router.post("/resend/{employee_id}", status_code=200)
async def resend_kbt_onboarding_email(
    employee_id: str,
    caller: dict = Depends(require_any_staff()),
    db: AsyncSession = Depends(get_db),
):
    """
    Resend the KBT onboarding email to an employee.
    Regenerates the signed download URL (72-hour window reset).
    Does NOT regenerate the KBT token (the existing binary still works).

    Use when:
    - Employee missed / deleted the original email
    - Download link expired
    - Admin wants to confirm delivery
    """
    # Fetch employee
    result = await db.execute(
        text("""
            SELECT id::text AS id, name, email, status, kbt_token_hash
            FROM employees
            WHERE id::text = :id AND deleted_at IS NULL
        """),
        {"id": employee_id},
    )
    row = result.fetchone()

    if not row:
        raise HTTPException(status_code=404, detail="Employee not found.")
    if row.status != "active":
        raise HTTPException(status_code=400, detail="Employee is not active.")
    if not row.kbt_token_hash:
        raise HTTPException(
            status_code=400,
            detail="No KBT token provisioned. Create the employee first or call GET /kbt/token/{id}.",
        )

    result = await run_kbt_onboarding(
        db=db,
        employee_id=row.id,
        employee_name=row.name,
        employee_email=row.email,
        created_by_id=str(caller.get("id", "system")),
    )

    if not result["email_sent"]:
        logger.error(f"[kbt-download] Resend failed: {result.get('error')}")
        raise HTTPException(
            status_code=500,
            detail=f"Email resend failed: {result.get('error', 'Unknown error')}",
        )

    logger.info(f"[kbt-download] Onboarding email resent for: {employee_id}")
    return {
        "ok": True,
        "message": f"Onboarding email resent to {row.email}",
        "download_url": result.get("download_url"),
    }
